### PR TITLE
Add linters

### PR DESCRIPTION
**Pull request by JulianaOsemeke**
Hello,
This is the first pull request of my capstone project. In this project, I have used HTML, CSS & BOOTSTRAP 5 to build a responsive conference page.

### CODE REVIEW

**Comment by marijanbrvar** [comment]
Hi Juliana,
Add package-lock.json to .gitignore :-)

**Comment by JulianaOsemeke** [comment]
Hello,
I have made requested changes as best I could. In this pull request I have done the following:
-I have added the font style used in the prototype
-I have added a high resolution image in the "middle section" depicting the purpose of the web page
-I have redone the footer
-The issue of responsivity of the mobile site was the most challenging. I  applied all the CSS best practices to eliminate the horizontal and vertical scroll bars. It would adjust but then revert back. Below is a screen shot  of the mobile view of the webpage.
mobile screenshot

**Comment by JulianaOsemeke** [comment]
Hello,
I have made the following changes as requested
1. I have removed the vertical and horizontal scrolls in the mobile and table version of the home, about and Get tickets page
2. I have changed the font-family to what was specified in the business requirements
3. I have added a high resolution image in the "middle section" depicting the purpose of the web page
4. I have redone the footer
5. I have modified the READ.ME.md as requested
N:B: On the github page where the project was deployed, I observed the trademark logo of the website I imported the Cocogoose font  from is displayed. However it does not do that locally. The screenshot in the README.md file shows this.

**Comment by JulianaOsemeke** [comment]
Hello,
I have made the following changes as requested
1. I have improved the main program section
2. I have made the page more responsive
3. I have redone the footer

**Pull request merged**
